spring:
   mail:
      host: smtp.gmail.com
      username: omkarssinha@gmail.com
      password: ****************
      port: 587
      properties:
         mail:
            smtp:
               starttls:
                  enable: true
               auth: true
               